/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package test00;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
        public static final int push_right_in=0x7f040002;
        public static final int push_right_out=0x7f040003;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int bar_color=0x7f050000;
        public static final int black2=0x7f050003;
        public static final int greeny=0x7f050004;
        public static final int white=0x7f050001;
        public static final int windows_color=0x7f050002;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int aii=0x7f020000;
        public static final int bg=0x7f020001;
        public static final int btn_bg_green=0x7f020002;
        public static final int btn_enable_green=0x7f020003;
        public static final int contact_list_normal=0x7f020004;
        public static final int contact_list_pressed=0x7f020005;
        public static final int default_face=0x7f020006;
        public static final int edittext_login=0x7f020007;
        public static final int find_normal=0x7f020008;
        public static final int find_pressed=0x7f020009;
        public static final int ic_launcher=0x7f02000a;
        public static final int icon_add=0x7f02000b;
        public static final int icon_back=0x7f02000c;
        public static final int icon_groupinfo=0x7f02000d;
        public static final int icon_titleaddfriend=0x7f02000e;
        public static final int profile_normal=0x7f02000f;
        public static final int profile_pressed=0x7f020010;
        public static final int shadow=0x7f020011;
        public static final int tab_contact_list=0x7f020012;
        public static final int tab_find=0x7f020013;
        public static final int tab_profile=0x7f020014;
        public static final int tab_weixin=0x7f020015;
        public static final int weixin_normal=0x7f020016;
        public static final int weixin_pressed=0x7f020017;
        public static final int wo=0x7f020018;
        public static final int wp=0x7f020019;
    }
    public static final class id {
        public static final int action_settings=0x7f0a0022;
        public static final int btn_login=0x7f0a0003;
        public static final int button1=0x7f0a0021;
        public static final int dl=0x7f0a0005;
        public static final int et_password=0x7f0a0001;
        public static final int et_usertel=0x7f0a0000;
        public static final int ib_contact_list=0x7f0a0011;
        public static final int ib_find=0x7f0a0015;
        public static final int ib_profile=0x7f0a0019;
        public static final int ib_weixin=0x7f0a000d;
        public static final int img_back=0x7f0a001c;
        public static final int img_right=0x7f0a001f;
        public static final int iv_icon=0x7f0a001d;
        public static final int layout_bar=0x7f0a0009;
        public static final int ll1=0x7f0a0006;
        public static final int lv=0x7f0a0008;
        public static final int main_bottom=0x7f0a000b;
        public static final int re_contact_list=0x7f0a0010;
        public static final int re_find=0x7f0a0014;
        public static final int re_profile=0x7f0a0018;
        public static final int re_weixin=0x7f0a000c;
        public static final int tv_contact_list=0x7f0a0012;
        public static final int tv_find=0x7f0a0016;
        public static final int tv_mail=0x7f0a0007;
        public static final int tv_password=0x7f0a0002;
        public static final int tv_profile=0x7f0a001a;
        public static final int tv_weixin=0x7f0a000e;
        public static final int tv_wenti=0x7f0a0004;
        public static final int txt_left=0x7f0a001b;
        public static final int txt_right=0x7f0a0020;
        public static final int txt_title=0x7f0a001e;
        public static final int unread_address_number=0x7f0a0013;
        public static final int unread_find_number=0x7f0a0017;
        public static final int unread_msg_number=0x7f0a000f;
        public static final int vp_content=0x7f0a000a;
    }
    public static final class layout {
        public static final int activity_login=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int item_text=0x7f030002;
        public static final int layout_bottom=0x7f030003;
        public static final int layout_title=0x7f030004;
        public static final int page_01=0x7f030005;
        public static final int page_02=0x7f030006;
        public static final int page_03=0x7f030007;
        public static final int page_04=0x7f030008;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class string {
        public static final int action_settings=0x7f070007;
        public static final int app_name=0x7f070000;
        public static final int chat=0x7f070001;
        public static final int contacts=0x7f070004;
        public static final int discover=0x7f070005;
        public static final int hello_world=0x7f070008;
        public static final int me=0x7f070006;
        public static final int password=0x7f070003;
        public static final int username=0x7f070002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
         */
        public static final int AppTheme=0x7f080002;
        /**  标题1样式 
         */
        public static final int txt_titleStyle1=0x7f080001;
    }
}
